### ISSUE TITLE
При покупке на 1 000 не возвращается 0

### ISSUE THREAD

**Issue by Mirzakaev-Timur** [Tima02121991/OsnovyAuto#1]
**Шаги воспроизведения:**
1. Создать проект grandle
2. Добавьте в зависимости JUnit:
>    https://github.com/MironovED/AT_homework_1.1/blob/b6b2a4bb7e68d4b2ecd4b04cfadc40b292adb86e/build.gradle#L13-L19

**Comment by Tima02121991** [comment]
> **Шаги воспроизведения:**
> 
> 1. Создать проект grandle
> 2. Добавьте в зависимости JUnit:
> 
> >https://github.com/Tima02121991/OsnovyAuto/blob/9ea73370590729fd4585d1f30ce1925f4b8edb2e/build.gradle#L17-24

**Comment by Tima02121991** [comment]
> **Шаги воспроизведения:**
> 
> 1. Создать проект grandle
> 2. Добавьте в зависимости JUnit:
> 
> > https://github.com/MironovED/AT_homework_1.1/blob/b6b2a4bb7e68d4b2ecd4b04cfadc40b292adb86e/build.gradle#L13-L19
